"""add address column to seller

Revision ID: 23968634a697
Revises: 65c92d448ac5
Create Date: 2026-09-21 22:41:06.673758

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23968634a697"
down_revision: str | Sequence[str] | None = "65c92d448ac5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seller", sa.Column("address", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller", "address")
    # ### end Alembic commands ###
