"""add client contact

Revision ID: 5b0091e92ef3
Revises:
Create Date: 2026-09-28 00:34:55.740144

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "5b0091e92ef3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("email", AutoString(), nullable=False),
        sa.Column("password_hash", AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("serviceable_zip_codes", sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_partner")),
    )
    op.create_table(
        "seller",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("email", AutoString(), nullable=False),
        sa.Column("password_hash", AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("address", AutoString(), nullable=True),
        sa.Column("zip_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller")),
    )
    op.create_table(
        "shipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_contact_email", AutoString(), nullable=False),
        sa.Column("client_contact_phone", sa.Integer(), nullable=True),
        sa.Column("content", AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("destination", sa.Integer(), nullable=False),
        sa.Column("estimated_delivery", sa.DateTime(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_partner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_partner_id"],
            ["delivery_partner.id"],
            name=op.f("fk_shipment_delivery_partner_id_delivery_partner"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["seller.id"], name=op.f("fk_shipment_seller_id_seller")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment")),
    )
    op.create_table(
        "shipment_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("location", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "placed",
                "in_transit",
                "out_for_delivery",
                "delivered",
                "cancelled",
                name="shipmentstatus",
            ),
            nullable=True,
        ),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
            name=op.f("fk_shipment_event_shipment_id_shipment"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_event")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment_event")
    op.drop_table("shipment")
    op.drop_table("seller")
    op.drop_table("delivery_partner")
    # ### end Alembic commands ###
