"""init

Revision ID: 65c92d448ac5
Revises:
Create Date: 2026-09-21 22:34:36.827823

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "65c92d448ac5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seller",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("email", AutoString(), nullable=False),
        sa.Column("password_hash", AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("destination", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "placed",
                "in_transit",
                "out_for_delivery",
                "delivered",
                name="shipmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("estimated_delivery", sa.DateTime(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment")
    op.drop_table("seller")
    # ### end Alembic commands ###
