"""add delivery partner table

Revision ID: 7023a74f844a
Revises:
Create Date: 2026-09-21 23:40:59.822786

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "7023a74f844a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("email", AutoString(), nullable=False),
        sa.Column("password_hash", AutoString(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("serviceable_zip_codes", sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "seller", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "shipment", sa.Column("delivery_partner_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        "fk_shipment_delivery_partner_id_delivery_partner",
        "shipment",
        "delivery_partner",
        ["delivery_partner_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_shipment_delivery_partner_id_delivery_partner",
        "shipment",
        type_="foreignkey",
    )
    op.drop_column("shipment", "delivery_partner_id")
    op.drop_column("seller", "created_at")

    # ### end Alembic commands ###
