"""change Shipment  client_contact_phone type

Revision ID: 7f5f83b81a3e
Revises: e8157ff16305
Create Date: 2026-10-05 14:30:12.989187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "7f5f83b81a3e"
down_revision: str | Sequence[str] | None = "e8157ff16305"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shipment",
        "client_contact_phone",
        existing_type=sa.INTEGER(),
        type_=AutoString(),
        existing_nullable=True,
        postgresql_using="client_contact_phone::varchar",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shipment",
        "client_contact_phone",
        existing_type=AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
