"""test

Revision ID: 6f5bf65dbf89
Revises: 7023a74f844a
Create Date: 2026-09-26 14:31:20.357994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "6f5bf65dbf89"
down_revision: str | Sequence[str] | None = "7023a74f844a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="shipmentstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
            name=op.f("fk_shipment_event_shipment_id_shipment"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_event")),
    )
    op.add_column(
        "seller",
        sa.Column("address", AutoString(), nullable=True),
    )
    op.add_column("seller", sa.Column("zip_code", sa.Integer(), nullable=True))
    op.drop_column("shipment", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipment",
        sa.Column(
            "status",
            postgresql.ENUM(
                "placed",
                "in_transit",
                "out_for_delivery",
                "delivered",
                name="shipmentstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("seller", "zip_code")
    op.drop_column("seller", "address")
    op.drop_table("shipment_event")
    # ### end Alembic commands ###
