"""add Review table

Revision ID: d76a315c934e
Revises: 7f5f83b81a3e
Create Date: 2026-10-07 10:27:47.349652

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "d76a315c934e"
down_revision: str | Sequence[str] | None = "7f5f83b81a3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", AutoString(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
            name=op.f("fk_review_shipment_id_shipment"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    # ### end Alembic commands ###
